name: intern_music_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  audioplayers: ^6.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/home_screen_image_1.jpeg
    - assets/images/slider1.png
    - assets/images/dummy_cover_1.png
    - assets/images/dummy_cover_2.png
    - assets/images/dummy_cover_3.png
    - assets/images/dummy_cover_4.png
    - assets/images/decoration_image.png
